# Generated by Django 5.0.7 on 2024-08-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Redoublant', 'Redoublant')], max_length=10)),
                ('contact_parent', models.CharField(max_length=15)),
                ('classe_actuelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='classes.classe')),
            ],
        ),
    ]
