# Generated by Django 5.0.7 on 2024-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_classes_cla_nom_265e0a_idx_and_more'),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['nom'], name='eleves_elev_nom_0d618a_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['matricule'], name='eleves_elev_matricu_a241b3_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['classe_actuelle'], name='eleves_elev_classe__91168e_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['statut'], name='eleves_elev_statut_e7b78e_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['sexe'], name='eleves_elev_sexe_73ec5d_idx'),
        ),
    ]
