# Generated by Django 5.0.7 on 2024-08-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='enseignant_titulaire',
        ),
    ]
