# Generated by Django 5.0.7 on 2024-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['nom'], name='classes_cla_nom_265e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['code'], name='classes_cla_code_9b7eb0_idx'),
        ),
    ]
