# Generated by Django 5.0.7 on 2024-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement_fr', models.CharField(max_length=255, verbose_name="Nom de l'établissement (Français)")),
                ('nom_etablissement_en', models.CharField(max_length=255, verbose_name="Nom de l'établissement (Anglais)")),
                ('bp_fr', models.CharField(max_length=255, verbose_name='Boîte Postale (Français)')),
                ('bp_en', models.CharField(max_length=255, verbose_name='Boîte Postale (Anglais)')),
                ('telephone_fr', models.CharField(max_length=255, verbose_name='Téléphone (Français)')),
                ('telephone_en', models.CharField(max_length=255, verbose_name='Téléphone (Anglais)')),
                ('ville_fr', models.CharField(max_length=255, verbose_name='Ville (Français)')),
                ('ville_en', models.CharField(max_length=255, verbose_name='Ville (Anglais)')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année Scolaire')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name="Logo de l'établissement")),
            ],
        ),
    ]
