# Generated by Django 5.0.7 on 2024-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresetablissement',
            name='logo',
            field=models.URLField(max_length=500),
        ),
    ]
