# Generated by Django 5.0.7 on 2024-09-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresetablissement',
            name='type_enseignement',
            field=models.CharField(choices=[('technique', 'Enseignement Technique'), ('bilingue', 'Enseignement Bilingue Ou Polyvalent'), ('general', 'Enseignement Général')], default='general', max_length=20, verbose_name="Type d'Enseignement"),
        ),
    ]
