# Generated by Django 5.0.7 on 2024-08-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_alter_parametresetablissement_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresetablissement',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL du Logo'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
