# Generated by Django 5.0.7 on 2024-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_parametresetablissement_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametresetablissement',
            name='logo',
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='bp_en',
            field=models.CharField(max_length=255, verbose_name='PO Box'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='bp_fr',
            field=models.CharField(max_length=255, verbose_name='Boîte Postale'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='nom_etablissement_en',
            field=models.CharField(max_length=255, verbose_name='Name of the School'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='nom_etablissement_fr',
            field=models.CharField(max_length=255, verbose_name="Nom de l'établissement"),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='telephone_en',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='telephone_fr',
            field=models.CharField(max_length=255, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='ville_en',
            field=models.CharField(max_length=255, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='parametresetablissement',
            name='ville_fr',
            field=models.CharField(max_length=255, verbose_name='Ville'),
        ),
    ]
