# Generated by Django 5.0.7 on 2024-08-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_remove_parametresetablissement_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametresetablissement',
            old_name='logo_url',
            new_name='logo',
        ),
    ]
