# Generated by Django 5.0.7 on 2024-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_rename_logo_url_parametresetablissement_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresetablissement',
            name='type_enseignement',
            field=models.CharField(choices=[('bilingue', 'Enseignement Bilingue'), ('technique', 'Enseignement Technique'), ('general', 'Enseignement Général')], default='general', max_length=20, verbose_name="Type d'Enseignement"),
        ),
    ]
