# Generated by Django 5.0.7 on 2024-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_parametresetablissement_type_enseignement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresetablissement',
            name='type_enseignement',
            field=models.CharField(choices=[('bilingue', 'bilingue'), ('technique', 'technique'), ('general', 'general')], default='general', max_length=20, verbose_name="Type d'Enseignement"),
        ),
    ]
