# Generated by Django 5.0.7 on 2024-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_alter_parametresetablissement_type_enseignement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresetablissement',
            name='type_enseignement',
            field=models.CharField(choices=[('Bilingue', 'Enseignement Bilingue'), ('Technique', 'Enseignement Technique'), ('General', 'Enseignement Général')], default='general', max_length=20, verbose_name="Type d'Enseignement"),
        ),
    ]
