# Generated by Django 5.0.7 on 2024-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_alter_parametresetablissement_type_enseignement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresetablissement',
            name='type_enseignement',
            field=models.CharField(choices=[('technique', 'Enseignement Technique'), ('bilingue', 'Enseignement Bilingue'), ('general', 'Enseignement Général')], default='general', max_length=20, verbose_name="Type d'Enseignement"),
        ),
    ]
