# Generated by Django 5.0.7 on 2024-08-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_classe_enseignant_titulaire'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='responsable_classe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='classes.classe'),
        ),
    ]
