# Generated by Django 5.0.7 on 2024-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_profilutilisateur_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(default='enseignant', max_length=50),
        ),
    ]
