# Generated by Django 5.0.7 on 2024-07-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_role_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
