# Generated by Django 5.0.7 on 2024-07-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_remove_profilutilisateur_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pedagogique'), ('SG', 'Surveillant General'), ('Adminitrateur', 'Administrateur')], default='enseignant', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.role'),
        ),
    ]
