# Generated by Django 5.0.7 on 2024-07-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_role_profilutilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pedagogique'), ('SG', 'Surveillant General'), ('Adminitrateur', 'Administrateur')], default='enseignant', max_length=50),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
