# Generated by Django 5.0.7 on 2024-07-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_profilutilisateur_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='code_de_securite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pedagogique'), ('SG', 'Surveillant General'), ('Adminitrateur', 'Administrateur')], default='enseignant', max_length=50, null=True),
        ),
    ]
