# Generated by Django 5.0.7 on 2024-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_alter_profilutilisateur_code_de_securite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pédagogique'), ('SG', 'Surveillant Général'), ('Administrateur', 'Administrateur')], default='enseignant', max_length=50, null=True),
        ),
    ]
