# Generated by Django 5.0.7 on 2024-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_profilutilisateur_nom_alter_profilutilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Enseignant', 'Enseignant'), ('AP', 'AP'), ('SG', 'SG'), ('Admin_', 'Admin_'), ('S_admin', 'S_admin')], default='enseignant', max_length=50, null=True),
        ),
    ]
