# Generated by Django 5.0.7 on 2024-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_alter_profilutilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pedagogique'), ('SG', 'Surveillant General'), ('Admin_', 'Admininistrateur')], default='enseignant', max_length=50, null=True),
        ),
    ]
