# Generated by Django 5.0.7 on 2024-07-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_profilutilisateur_inactif_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='inactif',
            field=models.BooleanField(default=False),
        ),
    ]
