# Generated by Django 5.0.7 on 2024-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_alter_profilutilisateur_inactif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='inactif',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
