# Generated by Django 5.0.7 on 2024-08-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0016_profilutilisateur_is_chef_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='chef_departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_departement', to='utilisateurs.profilutilisateur'),
        ),
    ]
