# Generated by Django 5.0.7 on 2024-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_alter_departement_chef_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
    ]
