# Generated by Django 5.0.7 on 2024-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0018_alter_matiere_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='departement',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='departement',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='utilisateurs.departement'),
        ),
    ]
