# Generated by Django 5.0.7 on 2024-08-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0019_remove_profilutilisateur_departement_delete_matiere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilutilisateur',
            old_name='departement',
            new_name='departements',
        ),
    ]
