# Generated by Django 5.0.7 on 2024-08-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0020_rename_departement_profilutilisateur_departements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='chef_departement',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='departements',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='is_chef_departement',
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pedagogique'), ('SG', 'Surveillant General'), ('Admin_', 'Administrateur')], default='Enseignant', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EnseignantDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chef_departement', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.departement')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.profilutilisateur')),
            ],
            options={
                'unique_together': {('enseignant', 'departement')},
            },
        ),
    ]
