# Generated by Django 5.0.7 on 2024-08-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0021_remove_departement_chef_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='chef_departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_departement', to='utilisateurs.profilutilisateur'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Enseignant', 'Enseignant'), ('AP', 'Animateur Pedagogique'), ('SG', 'Surveillant General'), ('Admin_', 'Admininistrateur')], default='Enseignant', max_length=50, null=True),
        ),
    ]
