# Generated by Django 5.0.7 on 2024-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0022_departement_chef_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True),
        ),
    ]
