# Generated by Django 5.0.7 on 2024-08-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0023_profilutilisateur_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='sexe',
        ),
    ]
