# Generated by Django 5.0.7 on 2024-08-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0025_profilutilisateur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='utilisateur_sg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='utilisateurs.profilutilisateur'),
        ),
    ]
