# Generated by Django 5.0.7 on 2024-08-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('cours', '0001_initial'),
        ('eleves', '0001_initial'),
        ('utilisateurs', '0022_departement_chef_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(choices=[('Seq1', 'Séquence 1'), ('Seq2', 'Séquence 2'), ('Seq3', 'Séquence 3'), ('Seq4', 'Séquence 4'), ('Seq5', 'Séquence 5')], max_length=10)),
                ('note', models.FloatField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='classes.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='utilisateurs.profilutilisateur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cours.matiere')),
            ],
            options={
                'unique_together': {('eleve', 'matiere', 'sequence')},
            },
        ),
    ]
