# Generated by Django 5.0.7 on 2024-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
        ('classes', '0001_initial'),
        ('eleves', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='sequence',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['eleve', 'sequence'], name='absences_ab_eleve_i_883447_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['classe', 'sequence'], name='absences_ab_classe__a1f8de_idx'),
        ),
    ]
