# Generated by Django 5.0.7 on 2024-08-25 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('duree_jours', models.IntegerField(default=365)),
                ('date_expiration', models.DateTimeField(default=datetime.datetime(2025, 8, 25, 11, 27, 15, 654082, tzinfo=datetime.timezone.utc))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
