# Generated by Django 5.0.7 on 2024-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('duree_minutes', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
