# Generated by Django 5.0.7 on 2024-08-18 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 10, 18, 16, 536829, tzinfo=datetime.timezone.utc)),
        ),
    ]
