# Generated by Django 5.0.7 on 2024-07-29 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='duree_minutes',
        ),
        migrations.AddField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 14, 30, 38, 668293, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='licence',
            name='duree_jours',
            field=models.IntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='licence',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
