# Generated by Django 5.0.7 on 2024-07-30 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_remove_licence_duree_minutes_licence_date_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 57, 41, 702698, tzinfo=datetime.timezone.utc)),
        ),
    ]
