# Generated by Django 5.0.7 on 2024-07-30 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0005_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 14, 22, 37, 476356, tzinfo=datetime.timezone.utc)),
        ),
    ]
