# Generated by Django 5.0.7 on 2024-09-01 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0005_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 14, 2, 15, 726540, tzinfo=datetime.timezone.utc)),
        ),
    ]
