# Generated by Django 5.0.7 on 2024-09-01 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0006_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 15, 58, 59, 519389, tzinfo=datetime.timezone.utc)),
        ),
    ]
