# Generated by Django 5.0.7 on 2024-09-01 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0007_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 23, 58, 8, 830396, tzinfo=datetime.timezone.utc)),
        ),
    ]
