# Generated by Django 5.0.7 on 2024-09-02 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0008_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 21, 6, 15, 795847, tzinfo=datetime.timezone.utc)),
        ),
    ]
