# Generated by Django 5.0.7 on 2024-07-31 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0008_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 22, 32, 47, 365297, tzinfo=datetime.timezone.utc)),
        ),
    ]
