# Generated by Django 5.0.7 on 2025-02-01 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0009_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 8, 48, 56, 240983, tzinfo=datetime.timezone.utc)),
        ),
    ]
