# Generated by Django 5.0.7 on 2024-08-02 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0015_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 10, 4, 20, 394833, tzinfo=datetime.timezone.utc)),
        ),
    ]
