# Generated by Django 5.0.7 on 2024-08-02 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0022_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 17, 11, 54, 396898, tzinfo=datetime.timezone.utc)),
        ),
    ]
