# Generated by Django 5.0.7 on 2024-08-07 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0023_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 16, 34, 2, 948384, tzinfo=datetime.timezone.utc)),
        ),
    ]
