# Generated by Django 5.0.7 on 2024-08-08 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0024_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 9, 55, 2, 183864, tzinfo=datetime.timezone.utc)),
        ),
    ]
