# Generated by Django 5.0.7 on 2024-08-08 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0027_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 13, 4, 34, 890594, tzinfo=datetime.timezone.utc)),
        ),
    ]
