# Generated by Django 5.0.7 on 2024-08-08 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0028_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 18, 2, 14, 206200, tzinfo=datetime.timezone.utc)),
        ),
    ]
