# Generated by Django 5.0.7 on 2024-08-14 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0043_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 7, 43, 41, 548148, tzinfo=datetime.timezone.utc)),
        ),
    ]
