# Generated by Django 5.0.7 on 2024-08-14 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0044_alter_licence_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 7, 45, 48, 728031, tzinfo=datetime.timezone.utc)),
        ),
    ]
