# Generated by Django 5.0.7 on 2024-08-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_alter_licence_date_expiration'),
        ('licences', '0092_alter_licence_date_expiration'),
    ]

    operations = [
    ]
