# Generated by Django 5.0.7 on 2024-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_remove_licence_duree_minutes_licence_date_expiration_and_more'),
        ('licences', '0093_merge_20240819_1520'),
    ]

    operations = [
    ]
