# Generated by Django 5.0.7 on 2024-08-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('utilisateurs', '0018_alter_matiere_coefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coefficient', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='classes.classe')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_matieres', to='utilisateurs.departement')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='utilisateurs.profilutilisateur')),
            ],
        ),
    ]
