# Generated by Django 5.0.7 on 2024-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='groupe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
