# Generated by Django 5.0.7 on 2024-08-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
    ]
