# Generated by Django 5.0.7 on 2024-08-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_auto_20240825_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereSequenceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(choices=[('Seq1', 'Séquence 1'), ('Seq2', 'Séquence 2'), ('Seq3', 'Séquence 3'), ('Seq4', 'Séquence 4'), ('Seq5', 'Séquence 5')], max_length=10)),
                ('note_complete', models.BooleanField(default=False)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_status', to='cours.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'sequence')},
            },
        ),
    ]
