# Generated by Django 5.0.7 on 2024-08-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_matieresequencestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='note_complete',
        ),
    ]
