# Generated by Django 5.0.7 on 2024-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_classes_cla_nom_265e0a_idx_and_more'),
        ('cours', '0004_remove_matiere_note_complete'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['nom'], name='cours_matie_nom_6ae08c_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['classe'], name='cours_matie_classe__9d1e16_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['departement'], name='cours_matie_departe_570d31_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['enseignant'], name='cours_matie_enseign_a21864_idx'),
        ),
    ]
